backend: compose
env-file: .env

defaults:
  profile: "${{ env.ENV }}"

profiles:
  prod:
    project-name: episcanner-prod
    config-path:
      - containers/compose-base.yaml
      - containers/compose-prod.yaml
    env-file: .env
    services:
      default:
        - wave
      available:
        - name: wave

  dev:
    project-name: episcanner-dev
    config-path:
      - containers/compose-base.yaml
      - containers/compose-dev.yaml
    env-file: .env
    services:
      default:
        - wave
      available:
        - name: wave

  ci:
    project-name: episcanner-dev
    config-path:
      - containers/compose-base.yaml
    env-file: .env
    services:
      default:
        - wave
      available:
        - name: wave
