
version: "3.9"
services:
  wave-app:
    build: .
    ports:
      - "10101:10101"
    volumes:
       # Mounting this file allows updates to the data files without restarting the container
      - ./data:/data/
