# Host
HOST_GID=$HOST_GID
HOST_UID=$HOST_UID
ENV=$ENV

# Used to fetch data from the database
PSQL_DB=$PSQL_DB
PSQL_DBF=$PSQL_DBF
PSQL_HOST=$PSQL_HOST
PSQL_PASSWORD=$PSQL_PASSWORD
PSQL_PORT=$PSQL_PORT
PSQL_USER=$PSQL_USER

ROOT_DIR=$ROOT_DIR
CTNR_EPISCANNER_DATA_DIR=$CTNR_EPISCANNER_DATA_DIR
HOST_EPISCANNER_DATA_DIR=$HOST_EPISCANNER_DATA_DIR

# Used by WaveServer
H2O_WAVE_BASE_URL=$H2O_WAVE_BASE_URL
H2O_WAVE_FORWARDED_HTTP_HEADERS=$H2O_WAVE_FORWARDED_HTTP_HEADERS
H2O_WAVE_BASE_URL=$H2O_WAVE_BASE_URL
H2O_WAVE_LISTEN=$H2O_WAVE_LISTEN
H2O_WAVE_ADDRESS=$H2O_WAVE_ADDRESS
