services:
  wave:
    entrypoint: ["wave", "run", "--no-autostart", "epi_scanner.app"]
    volumes:
      - ${HOST_EPISCANNER_ROOT}:${PROJECT_ROOT}
    networks:
      - infodengue-dev_infodengue

networks:
  infodengue-dev_infodengue:
    external: True
