services:
  wave:
    container_name: episcanner-${ENV}-wave
    hostname: episcanner-${ENV}-wave
    restart: unless-stopped
    build:
      context: ${HOST_EPISCANNER_ROOT:-..}
      dockerfile: ./containers/wave/Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
        PROJECT_ROOT: ${PROJECT_ROOT}
    env_file:
      - ../.env
    environment:
      - H2O_APP_ADDRESS=http://wave:8000
      - H2O_WAVE_LOG=error
      - H2O_WAVE_NO_LOG=1
      - H2O_WAVE_BASE_URL=/epi-scanner/
      - H2O_WAVE_LISTEN=:10101
      - H2O_WAVE_ADDRESS=http://wave:10101
      - H2O_WAVE_MAX_REQUEST_SIZE=100MB
    entrypoint: ["wave", "run", "--no-reload", "--no-autostart", "epi_scanner.app"]
    ports:
      - '10101:10101'
    volumes:
      - ${HOST_EPISCANNER_DATA_DIR}:${CTNR_EPISCANNER_DATA_DIR}
      - ${HOST_EPISCANNER_DUCKDB_DIR}:${CTNR_EPISCANNER_DUCKDB_DIR}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10101/epi-scanner/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - infodengue

networks:
  infodengue:
    driver: bridge
