name: EpiScanner Build

on: [pull_request]

env:
  HOST_GID: 1000
  HOST_UID: 1000
  ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.9"]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/env-base.yaml
        channels: conda-forge,nodefaults
        activate-environment: episcanner
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Install dependencies
      run: |
        poetry install

    - name: Create env file
      run: envsubst < env.tpl > .env

    - name: Build docker images
      run: |
         make containers-build

    - name: Docker start web
      run: |
        make containers-start

    - name: Docker waiting services
      run: |
        make containers-wait SERVICE=wave-app
